/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/paperplane/model.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Paperplane(props) {
  const { nodes, materials } = useGLTF('./models/paperplane/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials.White} />
    </group>
  )
}

useGLTF.preload('./models/paperplane/model.glb')
